- name: Install Gunicorn
  apt:
    name: gunicorn  # or the package manager relevant to your system
    state: present
  become: yes

- name: Create Gunicorn Socket
  copy:
    dest: /etc/systemd/system/gunicorn.socket
    content: |
      [Unit]
      Description=Gunicorn Socket

      [Socket]
      ListenStream=/opt/django-app/gunicorn.sock

      [Install]
      WantedBy=sockets.target
  become: yes

- name: Create Gunicorn Service
  copy:
    dest: /etc/systemd/system/gunicorn.service
    content: |
      [Unit]
      Description=Gunicorn Daemon for Your Django Application
      Requires=gunicorn.socket
      After=network.target

      [Service]
      WorkingDirectory=/opt/django-app
      # ExecStartPre=/bin/sleep 5
      # ExecStart=/usr/bin/gunicorn --workers 3 --bind unix:/opt/django-app/gunicorn.sock bridgebase.wsgi:application
      ExecStart=/usr/bin/gunicorn --workers 3 --bind {{ ansible_host }}:8000 bridgebase.wsgi:application
      [Install]
      WantedBy=multi-user.target
  become: yes

- name: Reload systemd daemon
  command: systemctl daemon-reload
  become: yes

# - name: Enable and Start Gunicorn Socket
#   systemd:
#     name: gunicorn.socket
#     enabled: yes
#     state: started
#   become: yes

- name: Start Gunicorn Service
  systemd:
    name: gunicorn.service
    enabled: yes
    state: started
  become: yes

